config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :sites

  root 'sites#index'

  get '/about-us', to: 'sites#about-us'
  get '/services', to: 'sites#services'
  get '/myths-advice', to: 'sites#myths-advice'
  get '/products', to: 'sites#products'
  get '/latest-projects', to: 'sites#latest-projects'
  get '/location', to: 'sites#location'
  get '/contact', to: 'contacts#new'
  get '/sitemap.xml', :to => redirect('/sitemap.xml')

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

      if @contact.save
        ContactMailer.contact_us_email(@contact).deliver_now
        redirect_to "/contact"
      else
        format.html { render :new }
      end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :subject, :message)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message, :size => "80x10" %>
  </div>
  <div class="actions">
    <%= f.submit "Contact Us" %>
  </div>
<% end %>

app/views/contacts/contact.html.erb
<html lang="en-US">

<!-- Start >> HTML Body -->
<body class="page page-id-15 page-template-default custom static pagelines default fixed_width ">
<div id="site" class="fullwidth">
	<div id="page" class="thepage">
				<div class="page-canvas">
						<header id="header" class="container-group">
				<div class="outline">


<!-- Branding | Section Template -->
<%= render '/layouts/branding' %>

<!-- NavBar | Section Template -->
<%= render '/layouts/navbar' %>


<!-- Content | Section Template -->
<section id="content" class="container no_clone section-content-area fix"><div class="texture"><div class="content"><div class="content-pad">		<div id="pagelines_content" class="fullwidth fix">

						<div id="column-wrap" class="fix">

								<div id="column-main" class="mcolumn fix">
					<div class="mcolumn-pad">


<!-- PostLoop | Section Template -->
<section id="postloop" class="copy no_clone section-postloop"><div class="copy-pad"><article class="post-15 page type-page status-publish hentry fpost post-number-1" id="post-15"><div class="hentry-pad"><div class="entry_wrap fix"><div class="entry_content"><h2><span style="color: #515151;">Contact Us</span></h2>
<p>We’re more than happy to answer your questions. Please feel free to call or email us.</p>
<h4>Phone</h4>
<p>541.286.4028 phone<br>
541.286.4027 fax</p>
<!-- <div class="wpcf7" id="wpcf7-f55-p15-o1"><form action="/contact/#wpcf7-f55-p15-o1" method="post" class="wpcf7-form" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="55">
<input type="hidden" name="_wpcf7_version" value="3.4">
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f55-p15-o1">
<input type="hidden" name="_wpnonce" value="13c759da69">
</div>
<p>Your Name (required)<br>
    <span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true"></span> </p>
<p>Your Email (required)<br>
    <span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true"></span> </p>
<p>Subject<br>
    <span class="wpcf7-form-control-wrap your-subject"><input type="text" name="your-subject" value="" size="40" class="wpcf7-form-control wpcf7-text"></span> </p>
<p>Your Message<br>
    <span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea"></textarea></span> </p>
<p><input type="submit" value="Send" class="wpcf7-form-control wpcf7-submit"><img class="ajax-loader" src="http://corvallisbattery.com/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden;"></p>
<div class="wpcf7-response-output wpcf7-display-none"></div></form></div> -->
</div></div></div></article><div class="clear"></div></div></section>					</div>
				</div>

							</div>
					</div>
</div></div></div></section>

<!-- Boxes | Section Template -->
<section id="boxes" class="container no_clone section-boxes fix"><div class="texture"><div class="content"><div class="content-pad"><div class="fboxes fix"><div class="plgrid "><div class="plgrid-pad"><div class="pprow grid-row fix "><div class="grid-element pp3 img_grid "><div class="grid-element-pad"><div id="fbox_49" class="fbox "><div class="media box-media inline_thumbs"><div class="blocks box-media-pad" style="min-height: 108px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div class="fboxgraphic img " style="width: 22%; max-width:65px"><img src="http://corvallisbattery.com/wp-content/uploads/2012/09/battery.png" alt="Cash for your batteries!" style="max-width: 100%"></div><div class="fboxinfo fix bd"><div class="fboxtitle"><h3>Cash for your batteries!</h3></div><div class="fboxtext">Simply drop off old lead-acid batteries. We pay top dollar!
<p> &nbsp; </p>  </div></div></span></div></div></div></div></div><div class="grid-element pp3 img_grid "><div class="grid-element-pad"><div id="fbox_46" class="fbox "><div class="media box-media inline_thumbs"><div class="blocks box-media-pad" style="min-height: 108px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div class="fboxgraphic img " style="width: 22%; max-width:65px"><img src="http://corvallisbattery.com/wp-content/uploads/2012/09/check_eng.png" alt="Check engine light?" style="max-width: 100%"></div><div class="fboxinfo fix bd"><div class="fboxtitle"><h3>Check engine light?</h3></div><div class="fboxtext">No problem... Stop in today and we will check it for free!
<!-- <p> &nbsp; </p>  </div></div></span></div></div></div></div></div><div class="grid-element pp3 img_grid pplast"><div class="grid-element-pad"><div id="fbox_4" class="fbox "><div class="media box-media inline_thumbs"><div class="blocks box-media-pad" style="min-height: 108px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div class="fboxgraphic img " style="width: 22%; max-width:65px"><img src="http://corvallisbattery.com/wp-content/uploads/2012/09/propane.png" alt="Refill your propane!" style="max-width: 100%"></div><div class="fboxinfo fix bd"><div class="fboxtitle"><h3>Refill your propane!</h3></div><div class="fboxtext">We make it convenient and easy to refill your propane tanks. -->

<p> &nbsp; </p>  </div></div></span></div></div></div></div></div></div></div></div></div></div></div></div></section>				</div>
								<div id="morefoot_area" class="container-group">
									</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>

	<footer id="footer" class="container-group">
		<div class="outline fix">


<!-- Morefoot Sidebars | Section Template -->
<section id="morefoot" class="container no_clone section-morefoot fix"><div class="texture"><div class="content"><div class="content-pad"><div class="morefoot fix"><div class="morefoot-pad"><div class="plgrid pagelines-grid"><div class="plgrid-pad"><div class="pprow grid-row fix "><div class="grid-element pp3 img_grid "><div class="grid-element-pad"><div class="morefoot-col"><div class="morefoot-col-pad blocks" style="min-height: 72px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div id="text-4" class="widget_text widget fix"><div class="widget-pad">			<div class="textwidget"></div>
		</div></div></span></div></div></div></div><div class="grid-element pp3 img_grid "><div class="grid-element-pad"><div class="morefoot-col"><div class="morefoot-col-pad blocks" style="min-height: 72px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div id="text-3" class="widget_text widget fix"><div class="widget-pad">			<div class="textwidget"><address style="text-align: center;">© 2015 Bend Battery.</address></div>
		</div></div></span></div></div></div></div><div class="grid-element pp3 img_grid pplast"><div class="grid-element-pad"><div class="morefoot-col"><div class="morefoot-col-pad blocks" style="min-height: 72px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div id="text-5" class="widget_text widget fix"><div class="widget-pad">			<div class="textwidget"></div>
		</div></div></span></div></div></div></div></div></div></div></div></div></div></div></div></section>		</div>
	</footer>
</div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40442468-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- Footer Scripts -->
<script type="text/javascript" src="http://corvallisbattery.com/wp-content/plugins/contact-form-7/includes/js/jquery.form.min.js?ver=3.32.0-2013.04.03"></script>
<script type="text/javascript">
/* <![CDATA[ */
var _wpcf7 = {"loaderUrl":"http:\/\/corvallisbattery.com\/wp-content\/plugins\/contact-form-7\/images\/ajax-loader.gif","sending":"Sending ..."};
/* ]]> */
</script>
<script type="text/javascript" src="http://corvallisbattery.com/wp-content/plugins/contact-form-7/includes/js/scripts.js?ver=3.4"></script>
<script type="text/javascript" src="http://s0.wp.com/wp-content/js/devicepx-jetpack.js?ver=201521"></script>
<script type="text/javascript" src="http://corvallisbattery.com/wp-content/themes/pagelines/js/script.bootstrap.min.js?ver=2.0.3"></script>
<script type="text/javascript" src="http://corvallisbattery.com/wp-content/themes/pagelines/js/script.blocks.js?ver=1.0.1"></script>


</body></html>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.subject %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<html lang="en-US">

<!-- Start >> HTML Body -->
<body class="page page-id-15 page-template-default custom static pagelines default fixed_width ">
<div id="site" class="fullwidth">
	<div id="page" class="thepage">
				<div class="page-canvas">
						<header id="header" class="container-group">
				<div class="outline">


<!-- Branding | Section Template -->
<%= render '/layouts/branding' %>

<!-- NavBar | Section Template -->
<%= render '/layouts/navbar' %>


<!-- Content | Section Template -->
<section id="content" class="container no_clone section-content-area fix"><div class="texture"><div class="content"><div class="content-pad">		<div id="pagelines_content" class="fullwidth fix">

						<div id="column-wrap" class="fix">

								<div id="column-main" class="mcolumn fix">
					<div class="mcolumn-pad">


<!-- PostLoop | Section Template -->
<section id="postloop" class="copy no_clone section-postloop"><div class="copy-pad"><article class="post-15 page type-page status-publish hentry fpost post-number-1" id="post-15"><div class="hentry-pad"><div class="entry_wrap fix"><div class="entry_content"><h2><span style="color: #515151;">Contact Us</span></h2>
<p>We are always standing by to answer any questions you may have about our

sales and services. Bend Battery is dedicated to customer satisfaction!</p>
<h4>Phone</h4>
<p>541.797.2242 phone<br>
</p>
<%= render 'form' %>
<!-- <div class="wpcf7" id="wpcf7-f55-p15-o1"><form action="/contact/#wpcf7-f55-p15-o1" method="post" class="wpcf7-form" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="55">
<input type="hidden" name="_wpcf7_version" value="3.4">
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f55-p15-o1">
<input type="hidden" name="_wpnonce" value="13c759da69">
</div>
<p>Your Name (required)<br>
    <span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true"></span> </p>
<p>Your Email (required)<br>
    <span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true"></span> </p>
<p>Subject<br>
    <span class="wpcf7-form-control-wrap your-subject"><input type="text" name="your-subject" value="" size="40" class="wpcf7-form-control wpcf7-text"></span> </p>
<p>Your Message<br>
    <span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea"></textarea></span> </p>
<p><input type="submit" value="Send" class="wpcf7-form-control wpcf7-submit"><img class="ajax-loader" src="http://corvallisbattery.com/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden;"></p>
<div class="wpcf7-response-output wpcf7-display-none"></div></form></div> -->
</div></div></div></article><div class="clear"></div></div></section>					</div>
				</div>

							</div>
					</div>
</div></div></div></section>

<!-- Boxes | Section Template -->
<section id="boxes" class="container no_clone section-boxes fix"><div class="texture"><div class="content"><div class="content-pad"><div class="fboxes fix"><div class="plgrid "><div class="plgrid-pad"><div class="pprow grid-row fix "><div class="grid-element pp3 img_grid "><div class="grid-element-pad"><div id="fbox_49" class="fbox "><div class="media box-media inline_thumbs"><div class="blocks box-media-pad" style="min-height: 108px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div class="fboxgraphic img " style="width: 22%; max-width:65px"><img src="http://corvallisbattery.com/wp-content/uploads/2012/09/battery.png" alt="Cash for your batteries!" style="max-width: 100%"></div><div class="fboxinfo fix bd"><div class="fboxtitle"><h3>Cash for your batteries!</h3></div><div class="fboxtext">Simply drop off old lead-acid batteries. We pay top dollar!
<p> &nbsp; </p>  </div></div></span></div></div></div></div></div><div class="grid-element pp3 img_grid "><div class="grid-element-pad"><div id="fbox_46" class="fbox "><div class="media box-media inline_thumbs"><div class="blocks box-media-pad" style="min-height: 108px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div class="fboxgraphic img " style="width: 22%; max-width:65px"><img src="http://corvallisbattery.com/wp-content/uploads/2012/09/check_eng.png" alt="Check engine light?" style="max-width: 100%"></div><div class="fboxinfo fix bd"><div class="fboxtitle"><h3>Check engine light?</h3></div><div class="fboxtext">No problem... Stop in today and we will check it for free!
<!-- <p> &nbsp; </p>  </div></div></span></div></div></div></div></div><div class="grid-element pp3 img_grid pplast"><div class="grid-element-pad"><div id="fbox_4" class="fbox "><div class="media box-media inline_thumbs"><div class="blocks box-media-pad" style="min-height: 108px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div class="fboxgraphic img " style="width: 22%; max-width:65px"><img src="http://corvallisbattery.com/wp-content/uploads/2012/09/propane.png" alt="Refill your propane!" style="max-width: 100%"></div><div class="fboxinfo fix bd"><div class="fboxtitle"><h3>Refill your propane!</h3></div><div class="fboxtext">We make it convenient and easy to refill your propane tanks. -->

<p> &nbsp; </p>  </div></div></span></div></div></div></div></div></div></div></div></div></div></div></div></section>				</div>
								<div id="morefoot_area" class="container-group">
									</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>

	<footer id="footer" class="container-group">
		<div class="outline fix">


<!-- Morefoot Sidebars | Section Template -->
<section id="morefoot" class="container no_clone section-morefoot fix"><div class="texture"><div class="content"><div class="content-pad"><div class="morefoot fix"><div class="morefoot-pad"><div class="plgrid pagelines-grid"><div class="plgrid-pad"><div class="pprow grid-row fix "><div class="grid-element pp3 img_grid "><div class="grid-element-pad"><div class="morefoot-col"><div class="morefoot-col-pad blocks" style="min-height: 72px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div id="text-4" class="widget_text widget fix"><div class="widget-pad">			<div class="textwidget"></div>
		</div></div></span></div></div></div></div><div class="grid-element pp3 img_grid "><div class="grid-element-pad"><div class="morefoot-col"><div class="morefoot-col-pad blocks" style="min-height: 72px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div id="text-3" class="widget_text widget fix"><div class="widget-pad">			<div class="textwidget"><address style="text-align: center;">© 2015 Bend Battery.</address></div>
		</div></div></span></div></div></div></div><div class="grid-element pp3 img_grid pplast"><div class="grid-element-pad"><div class="morefoot-col"><div class="morefoot-col-pad blocks" style="min-height: 72px;"><span class="equalizer-inner" style="display:block;margin:0;padding:0;"><div id="text-5" class="widget_text widget fix"><div class="widget-pad">			<div class="textwidget"></div>
		</div></div></span></div></div></div></div></div></div></div></div></div></div></div></div></section>		</div>
	</footer>
</div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40442468-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- Footer Scripts -->
<script type="text/javascript" src="http://corvallisbattery.com/wp-content/plugins/contact-form-7/includes/js/jquery.form.min.js?ver=3.32.0-2013.04.03"></script>
<script type="text/javascript">
/* <![CDATA[ */
var _wpcf7 = {"loaderUrl":"http:\/\/corvallisbattery.com\/wp-content\/plugins\/contact-form-7\/images\/ajax-loader.gif","sending":"Sending ..."};
/* ]]> */
</script>
<script type="text/javascript" src="http://corvallisbattery.com/wp-content/plugins/contact-form-7/includes/js/scripts.js?ver=3.4"></script>
<script type="text/javascript" src="http://s0.wp.com/wp-content/js/devicepx-jetpack.js?ver=201521"></script>
<script type="text/javascript" src="http://corvallisbattery.com/wp-content/themes/pagelines/js/script.bootstrap.min.js?ver=2.0.3"></script>
<script type="text/javascript" src="http://corvallisbattery.com/wp-content/themes/pagelines/js/script.blocks.js?ver=1.0.1"></script>


</body></html>

app/views/contacts/news.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @contact.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_branding.html.erb
<section id="branding" class="container no_clone section-branding fix">
  <div class="texture">
    <div class="content">
      <div class="content-pad">
        <div class="branding_wrap">
          <a class="plbrand mainlogo-link" href="<%= root_path %>" title="Bend Battery"><img class="mainlogo-img" src="<%= image_path('bend_battery_cv2.png') %>" alt="Bend Battery" scale="0" width="800"></a>
          <div class="icons" style="bottom: 42px; right: 2px;">
            <a target="_blank" href="https://www.facebook.com/Bendbattery?fref=ts" class="facebooklink">
              <img src="http://corvallisbattery.com/wp-content/themes/pagelines/sections/branding/facebook.png" alt="Facebook" scale="0">
            </a>
            <a target="_blank" href="https://twitter.com/BendBattery" class="twitterlink">
              <img src="http://corvallisbattery.com/wp-content/themes/pagelines/sections/branding/twitter.png" alt="twitter" scale="0">
            </a>
            <a target="_blank" href="https://instagram.com/bendbattery/" class="instagramlink">
              <img src="https://d3rnbxvnd0hlox.cloudfront.net/images/channels/28/icons/small.png" alt="instagram" scale="0">
            </a>
            <a target="_blank" href="https://plus.google.com/111057303083936764222/posts" class="google+link">
              <img src="http://www.precheck.com/sites/all/themes/precheck/images/google-plus-icon.png" alt="google+" scale="0">
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<section id="navbar" class="container no_clone section-navbar fix"><div class="content"><div class="content-pad">	<div class="navbar fix navbar-content-width  pl-color-black-trans">
	  <div class="navbar-inner ">
	    <div class="navbar-content-pad fix">

	      <a href="javascript:void(0)" class="nav-btn nav-btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>

	      		<div class="nav-collapse collapse">
	       <ul id="menu-main-nav" class="font-sub navline pldrop pull-left"><li id="menu-item-42" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-42"><a href="<%= about_us_path %>">ABOUT</a></li>
<li id="menu-item-36" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-36"><a href="<%= services_path %>">SERVICES</a></li>
<!-- <li id="menu-item-38" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-38"><a href="<%= myths_advice_path %>">MYTHS &amp; ADVICE</a></li> -->
<li id="menu-item-37" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-37"><a href="<%= products_path %>">PRODUCTS</a></li>
<li id="menu-item-35" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-35"><a href="<%= latest_projects_path %>">LATEST PROJECTS</a></li>
<li id="menu-item-39" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-39"><a href="<%= location_path %>">FIND US</a></li>
<li id="menu-item-41" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-41"><a href="/contact">CONTACT US</a></li>
</ul>				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
</div></div></section>				</div>
			</header>
						<div id="page-main" class="container-group">
				<div id="dynamic-content" class="outline">